### ISSUE TITLE
String and Text are not isomorphic

### ISSUE THREAD

**Issue by Bodigrim** [nikita-volkov/isomorphism-class#2]
```haskell
> Data.Text.unpack (Data.Text.pack "\57326")
"\65533"
```
It would be nice to document this.

**Comment by nikita-volkov** [comment]
Wow. That's news to me. Thanks for reporting.

Do you have any reference for more details on this?

**Comment by Bodigrim** [comment]
https://hackage.haskell.org/package/text-2.0/docs/Data-Text.html#v:pack hints this peculiarity, but not very explicit indeed.

**Comment by nikita-volkov** [comment]
Addressed in 0.1.0.1
